Avoid throwing error in created hook
I wanted to consolidate the try/catch error handling into the API call
in axios.js, but throwing an error from getMessage(), then calling
getMessage() from within the created() hook in MessageDisplay.vue
results in a Jest error:

```
FAIL  tests/unit/MessageDisplay.spec.js
  ● MessageDisplay › displays an error if getMessage fails
TypeError: Cannot read property 'textContent' of undefined
```

This is odd, because the element mounts and renders in the actual app.
In the browser console, the element content shows up:

```
>>> document.querySelector("[data-testid=message-error]").textContent
"Network Error: getMessage could not connect to the database."
```

Vue.js doesn't like errors in created() lifecycle hooks, but it should
only be a warning, and shouldn't make tests fail.